package assignments.week1.chapter2;

/*
--Exercise 11--

Modify your code from the previous exercise so that it could easily be modified to display a
different range of numbers (instead of 1234567890) and a different number of repetitions of those numbers
(instead of 60 total characters), with the vertical bars still matching up correctly.
Use class constants instead of “magic numbers.”
Here are some example outputs that could be generated by changing your constants:

    |    |    |    |    |    |    |    |    |    |
12340123401234012340123401234012340123401234012340
       |       |       |       |       |       |       |
12345670123456701234567012345670123456701234567012345670

*/

public class ExerciseEleven {
    private static final int RANGE_MAX = 7;
    private static final int REPETITIONS = 8;

    public static void main(String[] args) {
        for (int i = 0; i < REPETITIONS; i++) {
            for (int j = 0; j < RANGE_MAX; j++) {
                System.out.print(" ");
            }
            System.out.print("|");
        }
        System.out.println();
        for (int k = 0; k < REPETITIONS; k++) {
            for (int l = 1; l <= RANGE_MAX + 1; l++) {
                System.out.print(l % (RANGE_MAX + 1));
            }
        }
    }
}
